### ISSUE TITLE
Integrate with Talon voice?

### ISSUE THREAD

**Issue by username1290** [evfredericksen/StardewSpeak#1]
Hi, there's a voice control app called Talon voice
http://talonvoice.com 
it works on Linux, Windows and macOS, same as Stardew Valley. 

Do you know if there's a way to make your mod work with Talon?

**Comment by etfre** [comment]
It's certainly possible in the code that interacts with Stardew Valley is loosely coupled with the speech recognition (Dragonfly and Kaldi-Active-Grammar). It would still require significant code changes though to swap out and reintegrate the speech recognition piece, though.

**Comment by username1290** [comment]
Thanks!
